# Data Management - Assignment 8

## Data and Package Import

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_excel('data/impurity_dataset-training.xlsx')

## 1. Selecting specific subsets of time data

**Create a subset of the Dow dataset containing only data from Dec. 5 - Dec. 12, 2015.**  
The data should only include columns for `x1` to `x12`. You do not have to rename the columns.  
Print the first 5 rows of the new dataset.

In [3]:
df_datetime = df.set_index('Date')
df_oneweek = df_datetime['2015-12-05':'2015-12-12']
df_oneweek = df_oneweek[df_oneweek.columns[:12]]

In [4]:
df_oneweek.head(5)

,x1:Primary Column Reflux Flow,x2:Primary Column Tails Flow,x3:Input to Primary Column Bed 3 Flow,x4:Input to Primary Column Bed 2 Flow,x5:Primary Column Feed Flow from Feed Column,x6:Primary Column Make Flow,x7:Primary Column Base Level,x8:Primary Column Reflux Drum Pressure,x9:Primary Column Condenser Reflux Drum Level,x10:Primary Column Bed1 DP,x11:Primary Column Bed2 DP,x12:Primary Column Bed3 DP
Date,,,,,,,,,,,,
2015-12-05 00:00:00,329.358,47.0331,2104.92,1315.580,99.0892,96.2604,54.6870,40.9981,53.0726,6.84301,10.9171,8.78048
2015-12-05 01:00:00,328.920,47.0293,2097.57,1539.210,98.7808,96.1749,54.8310,40.9981,53.1708,6.83059,10.9171,8.96238
2015-12-05 02:00:00,328.865,47.0067,2097.19,958.648,98.8306,96.4169,54.6821,40.9745,53.0965,6.87476,10.9171,8.68794
2015-12-05 03:00:00,329.147,47.0218,2094.45,2041.020,98.9853,96.0839,54.6797,41.0169,53.0947,6.83088,11.1733,8.94487
2015-12-05 04:00:00,329.256,47.0370,2096.78,1984.860,98.4337,96.1642,54.6318,40.9981,53.1643,6.80179,10.9171,8.68794

**Print the dimensions of the new dataset.**

In [5]:
print(df_oneweek.shape)

(192, 12)

## 2. Removing and Dropping

**Create a version of the Dow dataset that does not contain any null or non-numeric values.**  
Print the first 5 rows of the new dataset.

In [6]:
def is_real_and_finite(x):
    if not np.isreal(x):
        return False
    elif not np.isfinite(x):
        return False
    elif pd.isnull(x):
        return False
    else:
        return True

In [7]:
numeric_map = df[df.columns[1:]].applymap(is_real_and_finite)
real_rows = numeric_map.all(axis = 1).values
df_dropped = df[real_rows]
df_dropped.head(5)

,Date,x1:Primary Column Reflux Flow,x2:Primary Column Tails Flow,x3:Input to Primary Column Bed 3 Flow,x4:Input to Primary Column Bed 2 Flow,x5:Primary Column Feed Flow from Feed Column,x6:Primary Column Make Flow,x7:Primary Column Base Level,x8:Primary Column Reflux Drum Pressure,x9:Primary Column Condenser Reflux Drum Level,...,x36: Feed Column Recycle Flow,x37: Feed Column Tails Flow to Primary Column,x38: Feed Column Calculated DP,x39: Feed Column Steam Flow,x40: Feed Column Tails Flow,Avg_Reactor_Outlet_Impurity,Avg_Delta_Composition Primary Column,y:Impurity,Primary Column Reflux/Feed Ratio,Primary Column Make/Reflux Ratio
0,2015-12-01 00:00:00,327.813,45.7920,2095.06,2156.01,98.5005,95.4674,54.3476,41.0121,52.2353,...,62.8707,45.0085,66.6604,8.68813,99.9614,5.38024,1.49709,1.77833,3.32803,0.291226
1,2015-12-01 01:00:00,322.970,46.1643,2101.00,2182.90,98.0014,94.9673,54.2247,41.0076,52.5378,...,62.8651,45.0085,66.5496,8.70683,99.8637,5.33345,1.51392,1.76964,3.29556,0.294044
2,2015-12-01 02:00:00,319.674,45.9927,2102.96,2151.39,98.8229,96.0785,54.6130,41.0451,52.0159,...,62.8656,45.0085,66.0599,8.69269,100.2490,5.37677,1.50634,1.76095,3.23481,0.300552
3,2015-12-01 03:00:00,327.223,46.0960,2101.37,2172.14,98.7733,96.1223,54.9153,41.0405,52.9477,...,62.8669,45.0085,67.9697,8.70482,100.3200,5.32315,1.47935,1.75226,3.31287,0.293752
4,2015-12-01 04:00:00,331.177,45.8493,2114.06,2157.77,99.3231,94.7521,54.0925,40.9934,53.0507,...,62.8673,45.0085,67.6454,8.70077,100.6590,5.28227,1.44489,1.74357,3.33435,0.286107

**Drop the `Avg_Delta_Composition Primary Column` variable.**

In [8]:
df_dropped_col = df_dropped.drop('Avg_Delta_Composition Primary Column', axis = 1)
df_dropped_col.head(5)

,Date,x1:Primary Column Reflux Flow,x2:Primary Column Tails Flow,x3:Input to Primary Column Bed 3 Flow,x4:Input to Primary Column Bed 2 Flow,x5:Primary Column Feed Flow from Feed Column,x6:Primary Column Make Flow,x7:Primary Column Base Level,x8:Primary Column Reflux Drum Pressure,x9:Primary Column Condenser Reflux Drum Level,...,x35: Secondary Column Tails Concentration,x36: Feed Column Recycle Flow,x37: Feed Column Tails Flow to Primary Column,x38: Feed Column Calculated DP,x39: Feed Column Steam Flow,x40: Feed Column Tails Flow,Avg_Reactor_Outlet_Impurity,y:Impurity,Primary Column Reflux/Feed Ratio,Primary Column Make/Reflux Ratio
0,2015-12-01 00:00:00,327.813,45.7920,2095.06,2156.01,98.5005,95.4674,54.3476,41.0121,52.2353,...,0.013060,62.8707,45.0085,66.6604,8.68813,99.9614,5.38024,1.77833,3.32803,0.291226
1,2015-12-01 01:00:00,322.970,46.1643,2101.00,2182.90,98.0014,94.9673,54.2247,41.0076,52.5378,...,0.013666,62.8651,45.0085,66.5496,8.70683,99.8637,5.33345,1.76964,3.29556,0.294044
2,2015-12-01 02:00:00,319.674,45.9927,2102.96,2151.39,98.8229,96.0785,54.6130,41.0451,52.0159,...,0.013498,62.8656,45.0085,66.0599,8.69269,100.2490,5.37677,1.76095,3.23481,0.300552
3,2015-12-01 03:00:00,327.223,46.0960,2101.37,2172.14,98.7733,96.1223,54.9153,41.0405,52.9477,...,0.013104,62.8669,45.0085,67.9697,8.70482,100.3200,5.32315,1.75226,3.31287,0.293752
4,2015-12-01 04:00:00,331.177,45.8493,2114.06,2157.77,99.3231,94.7521,54.0925,40.9934,53.0507,...,0.013085,62.8673,45.0085,67.6454,8.70077,100.6590,5.28227,1.74357,3.33435,0.286107

**Print the observations that have any null or non-numeric values.**  
You may want to use `pd.isnull()` function to check whether there are any null or non-numeric values.  
The expected result is just an empty `DataFrame`.

In [9]:
df_dropped_col[df_dropped_col.isnull().any(axis = 1)]

Empty DataFrame
Columns: [Date, x1:Primary Column Reflux Flow, x2:Primary Column Tails Flow, x3:Input to Primary Column Bed 3 Flow, x4:Input to Primary Column Bed 2 Flow, x5:Primary Column Feed Flow from Feed Column, x6:Primary Column Make Flow, x7:Primary Column Base Level, x8:Primary Column Reflux Drum Pressure, x9:Primary Column Condenser Reflux Drum Level, x10:Primary Column Bed1 DP, x11:Primary Column Bed2 DP, x12:Primary Column Bed3 DP, x13:Primary Column Bed4 DP, x14:Primary Column Base Pressure, x15:Primary Column Head Pressure, x16:Primary Column Tails Temperature, x17:Primary Column Tails Temperature 1, x18:Primary Column Bed 4 Temperature, x19:Primary Column Bed 3 Temperature, x20:Primary Column Bed 2 Temperature, x21:Primary Column Bed 1 Temperature, x22: Secondary Column Base Concentration, x23: Flow from Input to Secondary Column, x24: Secondary Column Tails Flow, x25: Secondary Column Tray DP, x26: Secondary Column Head Pressure, x27: Secondary Column Base Pressure, x28: Secondary Column Base Temperature, x29: Secondary Column Tray 3 Temperature, x30: Secondary Column Bed 1 Temperature, x31: Secondary Column Bed 2 Temperature, x32: Secondary Column Tray 2 Temperature, x33: Secondary Column Tray 1 Temperature, x34: Secondary Column Tails Temperature, x35: Secondary Column Tails Concentration, x36: Feed Column Recycle Flow, x37: Feed Column Tails Flow to Primary Column, x38: Feed Column Calculated DP, x39: Feed Column Steam Flow, x40: Feed Column Tails Flow, Avg_Reactor_Outlet_Impurity, y:Impurity, Primary Column Reflux/Feed Ratio, Primary Column Make/Reflux Ratio]
Index: []

[0 rows x 45 columns]

**Report the mean of** ***all numerical values*** **of this new dataset.**  
The output should be a single scalar value.

In [10]:
np.mean(df_dropped_col[df_dropped_col.columns[1:]].values)

207.1271177980023

**Report the variance of** ***all numerical values*** **of this new dataset.**  
The output should be a single scalar value.

In [11]:
np.var(df_dropped_col[df_dropped_col.columns[1:]].values)

346970.06549771875

## 3. Online Data Access

**Write a function that takes the simpler version of `json` file (e.g. `ethanol_simple.json`) as an argument and counts the number of C-H bonds in a given molecule.**

In [12]:
import json

def countCH(jsonFile):
    with open(jsonFile) as f:
        mol = json.load(f)
        
        bonds = mol['PC_Compounds'][0]['bonds']
        atoms = mol['PC_Compounds'][0]['atoms']
        
        n_bonds = len(bonds['aid1']) # get the number of bonds
        
        count = 0
        for i in range(n_bonds):
            if atoms['element'][bonds['aid1'][i] - 1] == 6 and atoms['element'][bonds['aid2'][i] - 1] == 1: # Check if the atom of aid1 is carbon and the atom of aid2 is hydrogen
                count += 1
            elif atoms['element'][bonds['aid1'][i] - 1] == 1 and atoms['element'][bonds['aid2'][i] - 1] == 6: # Vice versa
                count += 1
    
    return count

**Pass `ethanol_simple.json` to this function and report the number of C-H bonds in ethanol.**  
We all know that there are 5 C-H bonds in ethanol. The code block below should return 5.

In [13]:
count = countCH('data/ethanol_simple.json')
print(count)

5

**Write a function that takes the** ***CAS number*** **of a compound as an argument and returns the SMILES string.**  
The workflow should be:
- Use the PubChem RESTful API
- Extract the record as JSON
- Extract the SMILES string from this JSON
- Return the SMILES string

In [14]:
def returnSMILES(cas):
    r = requests.get('https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/{}/record/json'.format(cas)) # fill in this blank
    r_json = json.loads(r.text)
    
    smiles = r_json['PC_Compounds'][0]['props'][18]['value']['sval']
    return smiles

**Fetch the SMILES string-representation of phenol.**  
The CAS number of phenol is `108-95-2`.

In [15]:
import requests

smilesPhenol = returnSMILES('108-95-2')
print(smilesPhenol)

C1=CC=C(C=C1)O